window.OMO_CATALOG = {
  orderEmail: "orders@omo.stunning",
  currency: "USD",
  filters: ["All", "Soft", "Sparkle", "Navy", "3D", "Charms", "Minimal"],
  defaultOptionGroups: [
    {
      id: "fit",
      label: "Fit",
      choices: ["XS", "S", "M", "L", "Custom"],
    },
  ],
  products: [
    {
      id: "navy-orchid",
      name: "Navy Orchid",
      price: 42,
      image: "assets/navy-orchid.jpg",
      alt: "Navy blue and blush press-on nails with crystals and a white orchid charm",
      description: "Deep navy, soft blush, crystal trails, and a sculpted orchid.",
      tags: ["Navy", "3D", "Statement"],
      colors: ["#10263d", "#f2dbe4", "#f7f9fb"],
      optionGroups: [
        {
          id: "length",
          label: "Length",
          choices: ["Short", "Medium", { label: "Long", priceDelta: 4 }],
        },
      ],
    },
    {
      id: "crystal-blush",
      name: "Crystal Blush",
      price: 38,
      image: "assets/crystal-blush.jpg",
      alt: "Blush pink glitter press-on nails with crystal flakes and a silver ring charm",
      description: "Pink sparkle, glassy flakes, and a sweet ring detail.",
      tags: ["Sparkle", "3D", "Pink"],
      colors: ["#f0c5d4", "#f6e7bd", "#d8f4f1"],
    },
    {
      id: "gilded-pearl",
      name: "Gilded Pearl",
      price: 44,
      image: "assets/gilded-pearl.jpg",
      alt: "Neutral gold press-on nails with pearls, stones, and foil",
      description: "Champagne nude with pearls, gold foil, and tiny crystals.",
      tags: ["Pearl", "3D", "Neutral"],
      colors: ["#c29b52", "#efe3d2", "#f8f2e7"],
      optionGroups: [
        {
          id: "extras",
          label: "Extras",
          choices: ["As shown", { label: "Extra pearls", priceDelta: 6 }],
        },
      ],
    },
    {
      id: "soft-french",
      name: "Soft French",
      price: 34,
      image: "assets/soft-french.jpg",
      alt: "Milky white French press-on nails with rhinestone accents",
      description: "Milky French tips, gentle shimmer, and neat rhinestone dots.",
      tags: ["Soft", "Minimal", "Bridal"],
      colors: ["#fff8f2", "#e9f1f0", "#f3d6dc"],
    },
    {
      id: "ruby-hour",
      name: "Ruby Hour",
      price: 32,
      image: "assets/ruby-hour.jpg",
      alt: "Ruby red and amber press-on nails with glitter and one large crystal",
      description: "Warm red sparkle with an amber glow and a gem center.",
      tags: ["Bold", "Sparkle", "Short"],
      colors: ["#a5222f", "#d55b3a", "#f0c7b2"],
    },
    {
      id: "moonlit-glaze",
      name: "Moonlit Glaze",
      price: 36,
      image: "assets/moonlit-glaze.jpg",
      alt: "Nude glossy press-on nails with blue shimmer and crystal accents",
      description: "Barely-pink glaze, blue flash, and clear crystal accents.",
      tags: ["Soft", "Sparkle", "Minimal"],
      colors: ["#e8b9ab", "#9adce6", "#f7e5eb"],
    },
    {
      id: "charm-spark",
      name: "Charm Spark",
      price: 40,
      image: "assets/charm-spark.jpg",
      alt: "Gold glitter press-on nails with a playful white character charm",
      description: "Gold glitter, pearly blush, and one playful raised charm.",
      tags: ["Charms", "3D", "Playful"],
      colors: ["#d8b15d", "#f4d5dc", "#fff8f2"],
    },
    {
      id: "crystal-blush-alt",
      name: "Crystal Blush II",
      price: 38,
      image: "assets/crystal-blush-alt.jpg",
      alt: "Pink and iridescent glitter press-on nails with a silver ring charm",
      description: "A brighter take on blush shimmer with chunky iridescent flakes.",
      tags: ["Sparkle", "Pink", "Statement"],
      colors: ["#edabc0", "#f5df8b", "#cbeeea"],
    },
  ],
};
